import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import News from "@/components/News"; 
import Footer from "@/components/Footer";

// الخط اللي جه مع المشروع (لو عايزه)
import localFont from "next/font/local";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata
// Metadata
export const metadata: Metadata = {
  title: "MatchZone",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
    apple: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
return (
  <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <main className="px-2 md:px-16 md:py-2 text-Primary">

        {/* Navbar */}
        <Navbar />

        {/* Main Layout */}
        <section className="flex space-x-4">
          <Sidebar />
          {children}
          <News />
        </section>

        {/* Footer */}
        <Footer />

      </main>
    </body>
  </html>
);
}
